export { Account } from './Account';
export { Dashboard } from './Dashboard';
export { Login } from './Login';
export { Register } from './Register';
export { Settings } from './Settings';
export { NotFound } from './NotFound';
export { Home } from './Home/Home';
export { ProductDetails } from './Home/ProductDetails';
export { Cart } from './Home/Cart';